#!/bin/bash

echo "🔧 Generating .env.dev file..."

# Create .env.dev file with development defaults
cat > .env.dev << 'EOF'
# Development Environment Configuration
# Generated by generate-env-dev.sh
# 
# This file contains development-specific environment variables
# You can customize these values if needed

# Database Configuration (Development defaults)
MYSQL_ROOT_PASSWORD=dev_root_password
MYSQL_USER=dev_user
MYSQL_PASSWORD=dev_password
MYSQL_DATABASE=retro_app_dev

# Mercure JWT Secret (Development key - change for production!)
MERCURE_JWT_SECRET=dev_mercure_jwt_secret_key_change_in_production

# Redis Configuration (Development - no password)
REDIS_PASSWORD=

# Application Domain (Development)
APP_DOMAIN=localhost

# Email Configuration (Development - using MailHog)
MAILER_DSN=smtp://localhost:1025

# Additional Security Settings (Development key - change for production!)
APP_SECRET=dev_symfony_secret_key_change_in_production

# Environment Settings
APP_ENV=dev
APP_DEBUG=true

# Mercure URLs (Development)
MERCURE_URL=http://localhost:3000/.well-known/mercure
MERCURE_PUBLIC_URL=http://localhost:3000/.well-known/mercure
EOF

echo "✅ .env.dev file generated successfully!"
echo ""
echo "🔧 Development Environment Configuration:"
echo "- Database: retro_app_dev"
echo "- User: dev_user / Password: dev_password"
echo "- Root Password: dev_root_password"
echo "- Mercure: http://localhost:3000"
echo "- MailHog: http://localhost:8025"
echo ""
echo "⚠️  WARNING: These are development credentials only!"
echo "   Never use these credentials in production!"
echo ""
echo "🚀 To start development environment:"
echo "   ./setup-dev.sh"
