#!/bin/bash

echo "🔧 Generating .env.prod file..."

# Create .env.prod file with placeholders for sensitive data
cat > .env.prod << 'EOF'
# Production Environment Configuration
# Generated by generate-env-prod.sh
# 
# IMPORTANT: Fill in the actual values for database credentials and other sensitive data
# before deploying to production!

# Database Configuration
# Replace these placeholders with your actual MySQL credentials
MYSQL_ROOT_PASSWORD=your_mysql_root_password_here
MYSQL_USER=your_mysql_user_here
MYSQL_PASSWORD=your_mysql_password_here
MYSQL_DATABASE=retro_app

# Mercure JWT Secret
# Generate a strong, random key for Mercure authentication
# You can generate one with: openssl rand -base64 32
MERCURE_JWT_SECRET=your_mercure_jwt_secret_key_here

# Redis Configuration (if enabled)
# Replace with your actual Redis password
REDIS_PASSWORD=your_redis_password_here

# Application Domain
# Replace with your actual domain (without https://)
# Example: your-domain.com
APP_DOMAIN=your-domain.com

# Email Configuration (if using SMTP)
# Replace with your actual SMTP credentials
MAILER_DSN=smtp://username:password@smtp.example.com:587

# Additional Security Settings
# Generate a strong secret key for Symfony
# You can generate one with: php -r "echo bin2hex(random_bytes(32));"
APP_SECRET=your_symfony_secret_key_here

# Environment Settings
APP_ENV=prod
APP_DEBUG=false

# Mercure URLs (will be set automatically based on APP_DOMAIN)
MERCURE_URL=http://mercure/.well-known/mercure
MERCURE_PUBLIC_URL=https://${APP_DOMAIN}/.well-known/mercure
EOF

echo "✅ .env.prod file generated successfully!"
echo ""
echo "🔐 IMPORTANT SECURITY STEPS:"
echo "1. Edit .env.prod and replace all placeholder values with your actual credentials"
echo "2. Generate strong passwords for MYSQL_ROOT_PASSWORD, MYSQL_PASSWORD, and MERCURE_JWT_SECRET"
echo "3. Set your actual domain in APP_DOMAIN"
echo "4. Generate a strong APP_SECRET key"
echo "5. Never commit .env.prod to version control!"
echo ""
echo "📝 To generate secure keys:"
echo "   MERCURE_JWT_SECRET: openssl rand -base64 32"
echo "   APP_SECRET: php -r \"echo bin2hex(random_bytes(32));\""
echo ""
echo "🚀 After configuring .env.prod, run:"
echo "   ./deploy-prod.sh"
echo "   # or"
echo "   make prod"
echo ""
echo "🐳 Docker Production Environment:"
echo "   - All services run in Docker containers"
echo "   - MySQL, Redis, Nginx, PHP-FPM, Mercure, Prometheus"
echo "   - SSL/HTTPS support with certificates"
echo "   - Production-optimized configurations"
